// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGxqwwUKTRbkjtOUJMPzwH3rm7_sUZ2ho',
    appId: '1:639434438883:web:30ac9fde0cebf0336a6dd6',
    messagingSenderId: '639434438883',
    projectId: 'business-helper-f9467',
    authDomain: 'business-helper-f9467.firebaseapp.com',
    storageBucket: 'business-helper-f9467.firebasestorage.app',
    measurementId: 'G-SHDQP5BKTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtGEUOIPa5VOrmSafbjaB_0FVcvAIAyqQ',
    appId: '1:639434438883:android:6e15e6e9a7d698986a6dd6',
    messagingSenderId: '639434438883',
    projectId: 'business-helper-f9467',
    storageBucket: 'business-helper-f9467.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsK0o5MvXNpf1OXINQ__3SrBOfLRGhu-U',
    appId: '1:639434438883:ios:c672da4c369b837e6a6dd6',
    messagingSenderId: '639434438883',
    projectId: 'business-helper-f9467',
    storageBucket: 'business-helper-f9467.firebasestorage.app',
    iosBundleId: 'com.example.buisnesshelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsK0o5MvXNpf1OXINQ__3SrBOfLRGhu-U',
    appId: '1:639434438883:ios:c672da4c369b837e6a6dd6',
    messagingSenderId: '639434438883',
    projectId: 'business-helper-f9467',
    storageBucket: 'business-helper-f9467.firebasestorage.app',
    iosBundleId: 'com.example.buisnesshelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGxqwwUKTRbkjtOUJMPzwH3rm7_sUZ2ho',
    appId: '1:639434438883:web:16cb34e0953032896a6dd6',
    messagingSenderId: '639434438883',
    projectId: 'business-helper-f9467',
    authDomain: 'business-helper-f9467.firebaseapp.com',
    storageBucket: 'business-helper-f9467.firebasestorage.app',
    measurementId: 'G-RDL8256C6R',
  );
}
